import test from 'node:test';
import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import vm from 'node:vm';
import {gradeStableCheckpoint} from '../supabase/functions/_shared/academic-engine.ts';
import {assessmentBegin,assessmentSubmit} from '../supabase/functions/_shared/assessment-api.ts';
const bank=JSON.parse(readFileSync(new URL('../supabase/seed-data/ie-assessment-bank.v1.json',import.meta.url))).questions;
const sandbox={};vm.runInNewContext(readFileSync(new URL('../assets/js/universidade-assessment.js',import.meta.url),'utf8'),sandbox);
const A=sandbox.VCAssessment;
const ck=bank.filter(q=>q.module_no===1),final=bank.filter(q=>q.purpose==='final');
const answer=(questions,n)=>questions.map((q,i)=>({question_id:q.question_id,selected_option_id:i<n?q.correct_option_id:q.options.find(o=>o.option_id!==q.correct_option_id).option_id}));
test('banco:50checkpoints presentes',()=>assert.equal(bank.filter(q=>q.purpose==='checkpoint').length,50));
test('banco:cinco por módulo',()=>{for(let i=1;i<=10;i++)assert.equal(bank.filter(q=>q.module_no===i).length,5);});
test('banco:20finais integrativas em quatro movimentos',()=>{assert.equal(final.length,20);assert.equal(new Set(final.map(q=>q.movement)).size,4);assert.ok(final.every(q=>q.module_no===null));});
test('banco:quatro alternativas em cada item',()=>assert.ok(bank.every(q=>q.options.length===4)));
test('banco:exatamente uma correta por identidade',()=>assert.ok(bank.every(q=>q.options.filter(o=>o.option_id===q.correct_option_id).length===1)));
test('banco:correct_option_id pertence à questão',()=>assert.ok(bank.every(q=>q.options.some(o=>o.option_id===q.correct_option_id))));
test('banco:IDs editoriais/internos únicos e estáveis',()=>{assert.equal(new Set(bank.map(q=>q.editorial_id)).size,70);assert.equal(new Set(bank.map(q=>q.question_id)).size,70);assert.equal(new Set(bank.flatMap(q=>q.options.map(o=>o.option_id))).size,280);assert.match(bank[0].editorial_id,/IE-M01-Q01/);assert.equal(final[19].editorial_id,'IE-QF20');});
test('banco:C1–C7 válidas',()=>assert.ok(bank.every(q=>/^C[1-7]$/.test(q.competency_code))));
test('banco:N1–N3 e predominâncias adequadas',()=>{assert.ok(bank.every(q=>/^N[1-3]$/.test(q.difficulty)));assert.ok(bank.filter(q=>q.purpose==='checkpoint'&&q.difficulty==='N2').length>25);assert.ok(final.filter(q=>q.difficulty==='N3').length>10);});
test('checkpoint:3/5 falha',()=>assert.equal(A.simulate(ck,answer(ck,3),70).passed,false));
test('checkpoint:4/5 passa',()=>assert.equal(A.simulate(ck,answer(ck,4),70).passed,true));
test('prova:13/20 falha com65%',()=>{const r=A.simulate(final,answer(final,13),70);assert.equal(r.passed,false);assert.equal(r.scorePercent,65);});
test('prova:14/20 passa com70%',()=>{const r=A.simulate(final,answer(final,14),70);assert.equal(r.passed,true);assert.equal(r.scorePercent,70);});
test('randomização visual não altera gabarito estável',()=>{const shuffled=ck.map(q=>({...q,options:A.shuffle(q.options,()=>.1)}));assert.equal(A.simulate(shuffled,answer(shuffled,4),70).score,4);assert.notEqual(shuffled[0].options[0].option_id,ck[0].options[0].option_id);});
test('todos distratores têm feedback específico',()=>{for(const q of bank){assert.ok(q.options.every(o=>o.feedback.length>20));assert.equal(new Set(q.options.map(o=>o.feedback)).size,4);}});
test('retry permitido e histórico de dados não mutado',()=>{const original=JSON.stringify(ck);assert.equal(A.simulate(ck,answer(ck,3),70).retryAllowed,true);assert.equal(A.simulate(ck,answer(ck,4),70).passed,true);assert.equal(JSON.stringify(ck),original);});
test('snapshot não varia com mudança posterior da definição',()=>{const snap=structuredClone(ck);const edited=structuredClone(ck);edited[0].correct_option_id=edited[0].options.find(o=>o.option_id!==edited[0].correct_option_id).option_id;assert.equal(A.simulate(snap,answer(snap,5),70).score,5);assert.notEqual(edited[0].correct_option_id,snap[0].correct_option_id);});
test('banco versionado permanece Draft e conceitos incompletos são gaps',()=>{assert.ok(bank.every(q=>q.status==='draft'&&q.question_version===1));assert.ok(bank.filter(q=>q.editorial_gap).length===5);});
test('option de outra questão recusada na correção porID',()=>{const a=answer(ck,5);a[0].selected_option_id=ck[1].correct_option_id;assert.throws(()=>A.simulate(ck,a,70),/answers_invalid/);});
test('wrapper resolve aluno/matrícula recebidos somente do contexto',async()=>{let payload;await assessmentSubmit(async(_,__,o)=>{payload=JSON.parse(o.body);return {};},'resolved-a','resolved-e',{session_id:'11111111-1111-4111-8111-111111111111',answers:[],learner_id:'b',enrollment_id:'other',score:100});assert.equal(payload.p_actor,'resolved-a');assert.equal(payload.p_enrollment,'resolved-e');assert.equal('score' in payload,false);});
test('checkpoint wrapper usa propósito e módulo server-side',async()=>{let p;await assessmentBegin(async(_,__,o)=>{p=JSON.parse(o.body);return {};},'a','e','checkpoint',1);assert.equal(p.p_purpose,'checkpoint');assert.equal(p.p_module,1);});
test('prova wrapper usa sessão canônica com contexto',async()=>{let p;await assessmentBegin(async(_,__,o)=>{p=JSON.parse(o.body);return {};},'a','e','final',null);assert.equal(p.p_purpose,'final');assert.equal(p.p_module,null);});
test('correção não arredonda resultado para aprovação',()=>{const q=ck.slice(0,3);assert.equal(gradeStableCheckpoint(q,answer(q,2).map(a=>a.selected_option_id),67).passed,false);});
test('payload público nunca contém chave/feedback pré-resposta',()=>{for(const q of bank){const s=JSON.stringify(A.publicQuestion(q));assert.equal(/correct_option|correct_feedback|feedback|is_correct/.test(s),false);}});
test('preview simula sem qualquer IO',()=>{let writes=0;sandbox.fetch=()=>writes++;A.simulate(ck,answer(ck,5),70);assert.equal(writes,0);});
test('prova e projeto são notas acadêmicas distintas',()=>{const r=A.simulate(final,answer(final,14),70);assert.equal('emotional_score' in r,false);assert.equal('certificate' in r,false);assert.equal('project_approved' in r,false);});
