import test from 'node:test';import assert from 'node:assert/strict';import {readFileSync} from 'node:fs';
import {cycleWrite,cycleRead,cycleDefinitions} from '../supabase/functions/_shared/cycle-api.ts';
await import('../assets/js/universidade-evidence.js');await import('../assets/js/universidade-cycle.js');
const config=JSON.parse(readFileSync(new URL('../content/cycles/ie30.v1.json',import.meta.url),'utf8'));
const valid=schema=>Object.fromEntries(schema.sections.flatMap(s=>s.fields).map(f=>[f.field_key,f.type==='select'?f.options[0].value:f.type==='date'?'2026-10-06':'Fixture técnica anonimizada']));
for(const [key,schema] of Object.entries(config.forms))test(`ciclo: ${key} valida estrutura própria e rejeita identidade extra`,()=>{assert.equal(VCEvidence.validate(schema,valid(schema)).length,0);assert.ok(VCEvidence.validate(schema,{...valid(schema),learner_id:'other'}).length);assert.ok(schema.sections.flatMap(s=>s.fields).every(f=>f.label&&f.privacy_hint))});
for(const [elapsed,label] of [[0,'OBSERVAR'],[6,'OBSERVAR'],[7,'INTERROMPER'],[14,'SUBSTITUIR'],[21,'CONSOLIDAR'],[30,'CONSOLIDAR']])test(`fase pedagógica no dia decorrido ${elapsed}: ${label}`,()=>{const at=Date.parse('2026-10-06T12:00:00Z');assert.equal(VCCycles.phase(config,new Date(at-elapsed*86400000).toISOString(),at).label,label)});
test('rubrica oficial soma exatamente 100 e conserva nomes/pesos',()=>{assert.deepEqual(config.rubric.criteria.map(c=>c.max_points),[15,20,15,15,20,10,5]);assert.equal(config.rubric.criteria.reduce((n,c)=>n+c.max_points,0),100)});
for(const [score,approved] of [[68,false],[69,false],[69.999,false],[70,true],[70.1,true]])test(`rubrica ${score} ${approved?'aprova':'solicita revisão'}, sem arredondamento`,()=>{const points={padroes:10+Math.max(0,score-70),ferramentas:15,reflexao:10,coerencia:10,aplicabilidade:10,indicadores:Math.min(10,score-60),clareza:5};const result=VCCycles.rubric(config.rubric,points);assert.equal(result.total,score);assert.equal(result.approved,approved)});
test('rubrica recusa critério ausente, pontos acima do máximo, score enviado e NaN',()=>{const points=Object.fromEntries(config.rubric.criteria.map(c=>[c.key,c.max_points]));for(const bad of [{...points,clareza:6},{...points,padroes:NaN},{...points,total:100},{...points,clareza:undefined}])assert.ok(VCCycles.rubric(config.rubric,bad).errors.length)});
test('latest preserva histórico e usa somente versões atuais para contagem',()=>{const records=[{cycle_entry_id:'a',entry_type:'log',payload:{ferramenta:'PAUSA'}},{cycle_entry_id:'b',entry_type:'log',supersedes_entry_id:'a',payload:{ferramenta:'CLARO'}}];assert.equal(VCCycles.latest(records,'log').length,1);assert.equal(VCCycles.latest(records,'log')[0].cycle_entry_id,'b');assert.equal(records.length,2)});
test('nenhuma oportunidade relevante admite somente indicador de oportunidade e reflexão opcional',()=>{assert.equal(VCEvidence.validate(config.forms.weekly_review,{oportunidade:'nenhuma'}).length,0)});
test('setup limita contextos/sinais/estratégias/planos/indicadores a três e um alvo',()=>{const keys=config.forms.setup.sections.flatMap(s=>s.fields.map(f=>f.field_key));for(const prefix of ['contexto_','sinal_','estrategia_','plano_se_entao_','indicador_'])assert.equal(keys.filter(k=>new RegExp("^"+prefix+"[1-3]$").test(k)).length,3);assert.equal(keys.filter(k=>k==='comportamento_alvo').length,1);assert.ok(VCEvidence.validate(config.forms.setup,{...valid(config.forms.setup),indicador_4:'outro'}).length)});
test('política: preparação M7, start M9, 30/45 fixos, dois reenvios e revisão especial',()=>{assert.deepEqual([config.setup_after_module,config.start_after_module,config.duration_days,config.window_days,config.included_revisions],[7,9,30,45,2]);assert.deepEqual(config.required_applications,{PAUSA:3,CLARO:1,DECIDE:1})});
test('API ignora learner/enrollment/state/score e usa contexto do servidor',async()=>{let params;await cycleWrite(async(t,q,o)=>{assert.equal(t,'rpc/vc_university_cycle_write');params=JSON.parse(o.body);return {state:'setup'}},'a','e',{cycle_action:'setup_draft',payload:{},expected_version:0,learner_id:'b',enrollment_id:'b',state:'approved',score:100});assert.equal(params.p_actor,'a');assert.equal(params.p_enrollment,'e');assert.equal(params.p_action,'setup_draft');assert.equal(params.state,undefined);assert.equal(params.score,undefined)});
test('API rejeita transição arbitrária, versão inválida e request UUID ausente',async()=>{let writes=0;const db=async()=>writes++;for(const input of [{cycle_action:'approved',expected_version:0,payload:{}},{cycle_action:'setup_draft',expected_version:-1,payload:{}},{cycle_action:'submit',expected_version:0,payload:{}}])assert.equal((await cycleWrite(db,'a','e',input)).status,400);assert.equal(writes,0)});
test('API usa UUID idempotente e chave genérica do registro',async()=>{const id='33333333-3333-4333-8333-333333333333';await cycleWrite(async(t,q,o)=>{const p=JSON.parse(o.body);assert.equal(p.p_request,id);assert.equal(p.p_key,'log-1');return {}},'a','e',{cycle_action:'log',expected_version:1,payload:{},request_id:id,entry_key:'log-1'})});
test('leitura resolve matrícula server-side; preview lê configuração sem RPC de ciclo',async()=>{await cycleRead(async(t,q,o)=>{assert.equal(t,'rpc/vc_university_cycle_read');assert.deepEqual(JSON.parse(o.body),{p_actor:'a',p_enrollment:'e'});return {}},'a','e');await cycleDefinitions(async(t,q,o)=>{assert.equal(t,'vc_university_application_cycle_versions');assert.match(q,/in\.\(draft,review,published\)/);assert.equal(o,undefined);return []},'course','1.0',true)});
class Element{constructor(tag){this.tag=tag;this.children=[];this.events={};this.attributes={};this.textContent=''}append(...nodes){this.children.push(...nodes)}replaceChildren(...nodes){this.children=nodes}setAttribute(k,v){this.attributes[k]=v}removeAttribute(k){delete this.attributes[k]}addEventListener(k,fn){this.events[k]=fn}contains(n){return this===n||this.children.some(c=>c.contains?.(n))}all(){return [this,...this.children.flatMap(c=>c.all?.()||[])]}querySelector(s){if(s==='button[type=submit]')return this.all().find(n=>n.tag==='button'&&n.type==='submit');return this.all().find(n=>s.split(',').includes(n.tag))}focus(){this.focused=true}}
async function dom(fn){const prev=globalThis.document;globalThis.document={createElement:t=>new Element(t)};try{await fn()}finally{globalThis.document=prev}}
test('preview renderiza setup, quick log, 4 weekly, reflexão, E10 e rubrica sem escrita',()=>dom(async()=>{let writes=0;const root=VCCycles.render({definition:config,state:'not_started',entries:[]},{preview:true,write:()=>writes++});const buttons=root.all().filter(n=>n.tag==='button'&&n.onclick);for(const label of ['Preparar','Registro rápido','OBSERVAR','Reflexão final','Revisar visão','Professor']){const button=buttons.find(n=>n.textContent.startsWith(label));assert.ok(button);await button.onclick();assert.ok(root.all().some(n=>n.tag==='label'));assert.ok(!root.all().some(n=>n.textContent==='Rascunho · salvamento automático na sua conta.'));}assert.equal(writes,0);root.dispose()}));
test('rubrica mobile possui labels explícitos, numeric input e feedback estruturado',()=>dom(()=>{const root=VCCycles.renderReview({definition:{title:'E10',rubric:config.rubric},submission_id:'preview',current_revision:1,status:'submitted'},{preview:true});const nodes=root.all();assert.equal(nodes.filter(n=>n.tag==='input'&&n.type==='number').length,7);assert.equal(nodes.filter(n=>n.tag==='textarea').length,4);for(const input of nodes.filter(n=>['input','textarea'].includes(n.tag)))assert.ok(nodes.some(n=>n.tag==='label'&&n.htmlFor===input.id));}));
test('preview E10 simula submissão sem qualquer callback acadêmico',()=>dom(async()=>{let writes=0;const root=VCCycles.render({definition:config,state:'not_started',entries:[]},{preview:true,write:()=>writes++});await root.all().find(n=>n.textContent.startsWith('Revisar visão')).onclick();root.all().find(n=>n.tag==='input'&&n.type==='checkbox').checked=true;await root.all().find(n=>n.textContent==='Simular envio E10').onclick();assert.equal(writes,0);assert.ok(root.all().some(n=>n.textContent.includes('E10 simulada')));root.dispose()}));
test('autosave compartilhado mantém último payload e salva após debounce/flush',async()=>{let count=0,payload;const saver=VCEvidence.autosave(async p=>{count++;payload=p},()=>{},800);for(let i=0;i<20;i++)saver.change({reflexao:i});assert.equal(count,0);await saver.flush();assert.equal(count,1);assert.deepEqual(payload,{reflexao:19});saver.stop()});
