import test from 'node:test';
import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import {evidenceWrite,evidenceRead,evidenceDefinitions} from '../supabase/functions/_shared/evidence-api.ts';
await import('../assets/js/universidade-evidence.js');
const definitions=JSON.parse(readFileSync(new URL('../content/evidence/ie-e01-e09.v1.json',import.meta.url),'utf8'));
function valid(def){const data={};for(const s of def.form_schema.sections){const values=()=>Object.fromEntries(s.fields.map(f=>[f.field_key,f.type==='number'?f.min:f.type==='select'?f.options[0].value:'Fixture técnica anonimizada']));if(s.repeatable)data[s.section_key]=Array.from({length:s.min_items},values);else Object.assign(data,values())}return data}
for(const d of definitions)test(`${d.evidence_key.toUpperCase()} aceita estrutura completa com campos próprios`,()=>{assert.equal(VCEvidence.validate(d.form_schema,valid(d)).length,0);assert.ok(VCEvidence.validate(d.form_schema,{}).length);assert.ok(d.form_schema.sections.every(s=>s.fields.every(f=>f.label&&f.privacy_hint&&f.validation_rules)))});
for(const [key,group,count] of [['e02','registros',3],['e04','aplicacoes',2],['e05','situacoes',3],['e06','situacoes',2]])test(`${key} exige exatamente ${count} registros`,()=>{const d=definitions.find(d=>d.evidence_key===key),data=valid(d);data[group].pop();assert.ok(VCEvidence.validate(d.form_schema,data).some(e=>e.key===group));data[group]=Array.from({length:count+1},()=>valid(d)[group][0]);assert.ok(VCEvidence.validate(d.form_schema,data).some(e=>e.key===group))});
test('E01 intensidade subjetiva aceita 0 e 10; rejeita faixa, decimal e string',()=>{const d=definitions[0],data=valid(d);for(const n of [0,10]){data.intensidade_0_10=n;assert.equal(VCEvidence.validate(d.form_schema,data).length,0)}for(const n of [-1,11,1.5,'5']){data.intensidade_0_10=n;assert.ok(VCEvidence.validate(d.form_schema,data).length)}});
test('E06 certeza subjetiva aceita 0 e 100; rejeita faixa inválida',()=>{const d=definitions[5],data=valid(d);for(const n of [0,100]){data.situacoes[0].certeza_antes_0_100=n;assert.equal(VCEvidence.validate(d.form_schema,data).length,0)}for(const n of [-1,101]){data.situacoes[0].certeza_depois_0_100=n;assert.ok(VCEvidence.validate(d.form_schema,data).length)}});
test('campos desconhecidos e formatos inválidos não são aceitos',()=>{const d=definitions[0],data=valid(d);data.learner_id='arbitrary';assert.ok(VCEvidence.validate(d.form_schema,data).length);assert.ok(VCEvidence.validate(d.form_schema,[]).length);const e=valid(definitions[1]);e.registros[0]=null;assert.ok(VCEvidence.validate(definitions[1].form_schema,e).length)});
test('autosave agrupa digitação e permite recuperar o último conteúdo',async()=>{const writes=[],states=[];const saver=VCEvidence.autosave(async data=>writes.push(data),s=>states.push(s),1000);saver.change({contexto:'a'});saver.change({contexto:'ab'});saver.change({contexto:'abc'});assert.equal(writes.length,0);await saver.flush();assert.deepEqual(writes,[{contexto:'abc'}]);assert.equal(states.at(-1),'saved');saver.stop()});
test('autosave serializa alterações durante request e flush inclui a última geração',async()=>{const writes=[];let release;const blocked=new Promise(r=>release=r);const saver=VCEvidence.autosave(async d=>{writes.push(d);if(writes.length===1)await blocked},()=>{},1000);saver.change({a:1});const saving=saver.flush();await Promise.resolve();saver.change({a:2});release();await saving;assert.deepEqual(writes,[{a:1},{a:2}]);saver.stop()});
test('autosave falho mantém conteúdo pendente para nova tentativa',async()=>{let fail=true;const writes=[];const saver=VCEvidence.autosave(async d=>{if(fail)throw Error('offline');writes.push(d)},()=>{},1000);saver.change({a:1});await assert.rejects(saver.flush());assert.equal(saver.pending,true);fail=false;await saver.flush();assert.deepEqual(writes,[{a:1}]);saver.stop()});
test('API resolve contexto server-side e ignora IDs de matrícula/aluno/versão enviados',async()=>{let parameters;const result=await evidenceWrite(async(table,q,o)=>{parameters=JSON.parse(o.body);assert.equal(table,'rpc/vc_university_evidence_write');return {submission:{draft_version:1}}},'actual-user','actual-enrollment','actual-module',{action:'evidence_draft',payload:{contexto:'fixture'},expected_version:0,learner_id:'other',enrollment_id:'other',course_version:'other'});assert.equal(result.submission.draft_version,1);assert.equal(parameters.p_actor,'actual-user');assert.equal(parameters.p_enrollment,'actual-enrollment');assert.equal(parameters.p_module,'actual-module');assert.equal(parameters.p_action,'draft')});
test('submissão exige privacidade e UUID idempotente antes de chamar RPC',async()=>{let calls=0;const db=async()=>{calls++;return {}};for(const extra of [{},{request_id:crypto.randomUUID()},{privacy_confirmed:true,request_id:'bad'}])assert.equal((await evidenceWrite(db,'a','e','m',{action:'evidence_submit',payload:{},expected_version:0,...extra})).status,400);assert.equal(calls,0)});
test('submissão envia chave estável, versão esperada e payload para a transação',async()=>{const id=crypto.randomUUID();let params;await evidenceWrite(async(t,q,o)=>{params=JSON.parse(o.body);return {}},'a','e','m',{action:'evidence_submit',payload:valid(definitions[0]),expected_version:3,request_id:id,privacy_confirmed:true});assert.equal(params.p_request_id,id);assert.equal(params.p_expected_version,3);assert.equal(params.p_action,'submit')});
test('conflitos de versão e estrutura são retornados sem dados privados',async()=>{for(const [code,status] of [['draft_version_conflict',409],['evidence_structure_invalid',422]]){const response=await evidenceWrite(async()=>{throw Error(code)},'a','e','m',{action:'evidence_draft',payload:{},expected_version:0});assert.equal(response.error,code);assert.equal(response.status,status)}});
class Element{constructor(tag){this.tag=tag;this.children=[];this.events={};this.attributes={};this.textContent=''}append(...nodes){this.children.push(...nodes)}replaceChildren(...nodes){this.children=nodes}setAttribute(k,v){this.attributes[k]=v}removeAttribute(k){delete this.attributes[k]}addEventListener(k,fn){this.events[k]=fn}contains(n){return this===n||this.children.some(c=>c.contains?.(n))}querySelector(selector){return this.all().find(n=>selector.split(',').includes(n.tag))}all(){return this.children.flatMap(c=>[c,...c.all()])}focus(){this.focused=true}}
async function dom(fn){const prior=globalThis.document;globalThis.document={createElement:t=>new Element(t)};try{await fn()}finally{globalThis.document=prior}}
test('mobile renderer tem etapas, labels, faixas, touch CSS e revisão com aviso exato',()=>dom(()=>{for(const d of definitions){const form=VCEvidence.render(d,{preview:true});const nodes=form.all();assert.ok(nodes.filter(n=>n.tag==='fieldset').length>0);for(const input of nodes.filter(n=>['textarea','select'].includes(n.tag)||(n.tag==='input'&&n.type==='number'))){assert.ok(nodes.some(n=>n.tag==='label'&&n.htmlFor===input.id));assert.ok(input.attributes['aria-describedby'])}assert.ok(nodes.some(n=>n.textContent===d.form_schema.privacy_notice));assert.ok(nodes.some(n=>n.tag==='button'&&n.textContent==='Simular envio'));form.dispose()}const css=readFileSync(new URL('../assets/css/universidade.css',import.meta.url),'utf8');assert.match(css,/@media\(max-width:600px\)/);assert.match(css,/min-height:48px/);assert.match(css,/min-height:140px/)}));
test('preview válido simula sem save, submit, revisions ou eventos',()=>dom(async()=>{let writes=0;const d=definitions[0],form=VCEvidence.render(d,{preview:true,submission:{draft_data:valid(d),draft_version:0,status:'draft'},save:()=>writes++,submit:()=>writes++});const nodes=form.all();nodes.find(n=>n.type==='checkbox').checked=true;await nodes.find(n=>n.tag==='form').events.submit({preventDefault(){}});assert.equal(writes,0);assert.ok(nodes.some(n=>n.textContent.includes('Simulação válida')));form.dispose()}));
test('erros de campo são associados e foco leva ao primeiro campo inválido',()=>dom(async()=>{const form=VCEvidence.render(definitions[0],{preview:true});await form.all().find(n=>n.tag==='form').events.submit({preventDefault(){}});const first=form.all().find(n=>n.tag==='textarea');assert.equal(first.attributes['aria-invalid'],'true');assert.equal(first.focused,true);form.dispose()}));
test('revisão submetida fica somente leitura no renderer',()=>dom(()=>{const form=VCEvidence.render(definitions[0],{submission:{draft_data:valid(definitions[0]),status:'submitted',current_revision:1,draft_version:2}});assert.ok(form.all().filter(n=>n.tag==='textarea').every(n=>n.disabled));assert.equal(form.all().find(n=>n.type==='submit').disabled,true);form.dispose()}));
test('refresh durante autosave preserva alterações posteriores ao payload em trânsito',()=>dom(()=>{const original=globalThis.sessionStorage;const server=valid(definitions[0]),pending={...server,contexto:'Texto posterior ainda não confirmado pelo servidor'};const cache={version:1,data:pending,in_flight_payload:{...server}};globalThis.sessionStorage={getItem:()=>JSON.stringify(cache),setItem(){},removeItem(){}};try{const form=VCEvidence.render(definitions[0],{submission:{draft_data:server,draft_version:2,status:'draft'},storageKey:'fixture',save:async()=>({submission:{draft_version:3}})});assert.equal(form.all().find(n=>n.id?.endsWith('-contexto')).value,pending.contexto);form.dispose()}finally{globalThis.sessionStorage=original}}));
test('cache de outra versão não sobrescreve conteúdo remoto divergente',()=>dom(()=>{const original=globalThis.sessionStorage,server=valid(definitions[0]);globalThis.sessionStorage={getItem:()=>JSON.stringify({version:1,data:{...server,contexto:'Outra tela'},in_flight_payload:{contexto:'Divergente'}}),setItem(){},removeItem(){}};try{const form=VCEvidence.render(definitions[0],{submission:{draft_data:server,draft_version:2,status:'draft'},storageKey:'fixture',save:async()=>({submission:{draft_version:3}})});assert.equal(form.all().find(n=>n.id?.endsWith('-contexto')).value,server.contexto);form.dispose()}finally{globalThis.sessionStorage=original}}));
test('limite de payload conta bytes UTF-8, inclusive em português e símbolos',()=>{const d=definitions[4],data=valid(d);for(const section of d.form_schema.sections){for(const item of section.repeatable?data[section.section_key]:[data])for(const field of section.fields)item[field.field_key]='界'.repeat(1200)}assert.ok(JSON.stringify(data).length<65536);assert.ok(VCEvidence.validate(d.form_schema,data).some(e=>e.key==='form'))});
